server:
  port: 8080
spring:
  application:
    name: api-pricing-service
    version: 1.0.0
  cloud:
    vault:
      uri: '${VAULT_URL}'
      authentication: '${VAULT_TYPE_TOKEN}'
      token: '${VAULT_TOKEN}'
      kv:
        enabled: true
        backend: secret
        default-context: '${VAULT_SECRET}'
  webflux:
    base-path: /api/v1/pricing
  datasource:
    driver-class-name: org.h2.Driver
    initialization-mode: always
  sql:
    init:
      mode: always
      schema-locations:
        - classpath:/db/schema.sql
      data-locations:
        - classpath:/db/data.sql
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  data:
    redis:
      port: 6379

logging:
  pattern:
    console: "? [api-pricing-service] %d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  level:
    root: INFO
    org.springframework.web: ERROR
    org.springframework.cloud.vault: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info,error,prometheus,metrics,h2-console
  endpoint:
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
  health:
    defaults:
      enabled: true