name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Grant execute permission for Gradle wrapper
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew clean build --no-daemon

      - name: Generated open api
        run: ./gradlew openApiGenerate

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Authenticate to GCP using service account JSON
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
          GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}

        run: |
          echo "$GCP_SA_KEY" > sa-key.json
          gcloud auth activate-service-account --key-file=sa-key.json
          gcloud config set project "$GCP_PROJECT_ID"
          rm sa-key.json

      - name: List Artifact Registry repositories
        run: gcloud artifacts repositories list --location=${{ secrets.REGION }}

      - name: Configure Docker authentication
        run: gcloud auth configure-docker ${{ secrets.REGION }}-docker.pkg.dev --quiet

      - name: Print set secrets
        run: |
          REGION="${{ secrets.REGION }}"
          PROJECT_ID="${{ secrets.GCP_PROJECT_ID }}"
          
          echo "📍 REGION=${{ secrets.REGION }}"
          echo "📍 PROJECT_ID=${{ secrets.PROJECT_ID }}"
          echo "📍 GITHUB_SHA=$GITHUB_SHA"

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/api-pricing-repo/api-pricing-service:$GITHUB_SHA .

      - name: Push Docker image to Google Container Registry
        run: |
          docker push ${{ secrets.REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/api-pricing-repo/api-pricing-service:$GITHUB_SHA

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy api-pricing-service \
            --image ${{ secrets.REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/api-pricing-repo/api-pricing-service:$GITHUB_SHA \
            --region ${{ secrets.REGION }} \
            --platform managed \
            --allow-unauthenticated \
            --set-env-vars URL_DATABASE=${{ secrets.URL_DATABASE }},PORT=${{ secrets.PORT }},USER_DATABASE=${{ secrets.USER_DATABASE }}

